[project]
name = "mnist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.8",
    "mnist-datasets>=0.14",
    "numpy>=2.3.5",
    "tk>=0.1.0",
]
